[workspace]
members = ["encoding_utils_lib", "simple-ssimu2", "frame-boost", "vpy-files"]
resolver = "2"

[workspace.dependencies]
eyre = "0.6.12"
rayon = "1.10.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0"
vapoursynth4-rs = { features = [
    "link-library",
], git = "https://github.com/inflation/vapoursynth4-rs", rev = "e81e1ab17d8ad9625f4ee6cd309a658eeeb1b4c7" }
clap = { version = "4.5.37", features = ["derive"] }
